### PR TITLE
Make a version of the plugin that doesn't force existing Test classes to be scalatest, but rather adds a scalatest task of type Test.

### PR DESCRIPTION
**Pull request by scr**
This adds a new plugin id `'com.github.maiflai.scalatest.task'` so that folks can still use the old one to ONLY use scalatest.  When using the new plugin, instead of altering all existing tasks of type `Test`, this adds a new task named `'scalatest'` of type Test, which `check` depends on, thus allowing both frameworks to run in the same project and reduces complexity of setting up a multi-project build with the appropriate configurations to share testRuntimeClasspath, etc.

### CODE REVIEW

**Comment by scr** [comment]
Man, I don't get it - these tests pass just fine on my machine(s).  For some reason on travis they fail and I'm totally blind to the errors - trying to dump errors now on latest build, using info in https://github.com/lhotari/travis-gradle-test-failures-to-console

**Comment by scr** [comment]
Wow - ok - so apparently the example that I made using testng pulled in some conflicting jCommander module which failed.  It's very helpful to have the errors logged via that after_failure declaration in travis.yml.

So now everything passes and proves that you can use junit AND scalatest in the same project, which was the whole point!

@maiflai - please approve and merge at your earliest convenience (or send requests for change if you see something I should do differently).

**Comment by maiflai** [comment]
Firstly - thanks very much, it looks like you've had a bit of a struggle :-/

This looks like it addresses https://github.com/maiflai/gradle-scalatest/issues/14 which was closed because I didn't want to support mixing test frameworks in a single module.

I can see that it's trickier to perform the refactoring when you have a separate project, but I still think that it is easier to actually finish when you can see a legacy module shrinking. 

Supporting multiple frameworks means that developers can continue to move in opposite directions.

That said, the plugin has moved on slightly which makes the workaround suggested in that issue cumbersome and I recognise that others prefer the mixed approach.

With specific regard to this implementation - I'm not sure that having a separate plugin id in the same jar is a good idea; I think it won't work with the`plugin` DSL. Please could you have a look at controlling this with an extension property rather than a separate plugin?

Thanks again,
Stu

**Comment by scr** [comment]
Supporting multiple frameworks means that developers have a path to move to the desired one.  Making the plugin provide building blocks that may be reused make it more extensible/useable to use-cases that may not have been considered at first.

The complications I hit were mostly all about Travis - it built fine for me locally - and I think there may be some java7 stuff that caused complications with TestNG's transitive dependency on JCommander.  I had also written some testing in other projects using spock and the gradleTestkit() and tried to do that here, but rolled that back mostly out of suspicion and simplification of the PR.

Regarding extension property, I'll see what I can do - that seems to be a little tricky because it may require some configuration at plugin application, and more after evaluation (to avoid hijacking the test task).

FWIW, I'm using a piece of this in my projects and it work well for me now, but I'll try to revisit this patch to bring it in line with your suggestions and the latest codebase.

Thanks.

**Comment by maiflai** [comment]
Glad to hear you've got something that works - I had a quick go at the extension property and found it tricky too.

I suspect the path of least resistance is to always add a `scalatest` task, but if done naively then the test output directories would change for existing users, and the `test` task would always run but not execute tests for pure ScalaTest users.

It might be possible to configure the `scalatest` task to write to the `test` output directories when the extension is configured accordingly. 

I'll see if I can come up with something over the weekend.

Thanks.
Stu.

**Comment by lbergelson** [comment]
We would be interested in this.  We have a mixed scala/java test suite and would like to run testng for the java and scalatest for the scala.  We're currently creating a base class which both tests implement that gets picked up by scalatest and run, but it's caused  problems for us.  People forget to have their test classes extend it, we're hitting problems with the test filtering ( #28), and we get confusing output to the console.  A plugin that adds a new scalatest task without replacing test would be ideal for us.  It looks like maybe that's not the direction this plugin want's to go in, but maybe a parallel plugin for mixed use case would be a good idea.

**Comment by scr** [comment]
@lbergelson - https://gist.github.com/scr/5aaaf6387c1f52de4b9d7e449bbf0d1f shows a local version of the PR - if you don't mind adding to your own buildSrc, it works for us

**Comment by maiflai** [comment]
Hi,

Thanks for the pointers, I think I've managed to incorporate this in a way that works with the plugins repository.

Please would it be possible to take a look at https://github.com/maiflai/gradle-scalatest/releases/tag/0.17 and see if it addresses the issue?

Stu

**Comment by maiflai** [comment]
Adding this to a gradle.properties file in the root of the project should enable the mode.
```
com.github.maiflai.gradle-scalatest.mode = append
```

**Pull request closed without merging**
